### ISSUE TITLE
Key combinations in SearchDialog component not working on Mac

### ISSUE THREAD

**Issue by ozhanefemeral** [ozhanefemeral/visual-ts#22]
### **Is your feature request related to a problem? Please describe.**
Combining ⌥ + any numbers from 1 to 9 should be selecting a function from the list and add it to the CodeGeneratorContext. This works flawlessly on Windows - Chrome but not on Mac - Chrome.

![image](https://github.com/user-attachments/assets/82fce37f-fd87-49e3-a361-4ad8685487e3)

### **Describe the solution you'd like**
Create a solution that is OS/Browser agnostic and consistent. Refactor all keyboard event handlers within SearchDialog based on that solution. Feel free to use another library 

Feel free to share your thoughts or create a PR for this issue 🤞

**Comment by AhmetSBulbul** [comment]
<img width="578" alt="image" src="https://github.com/user-attachments/assets/55e18587-618e-41b0-b50e-1b3c72e2f015">

Using option key modifies the value of event.key, so instead of using option we can use control key or another solution is using code value instead of key. For example the code always will be Digit1 but the key can be "1" or "i" or something else, removing the Digit prefix will solve the issue but in searchable lists field is updated with the value instead of executing shortcut.

I'm gonna open PR with using control key solution.

I'm adding the "using event.code instead of key and clear the Digit prefix" solution here as a referance if anyone needs to use altKey for shortcut later.

<img width="632" alt="image" src="https://github.com/user-attachments/assets/ac632688-5376-48e0-8153-7da7f0fd9583">

<img width="408" alt="image" src="https://github.com/user-attachments/assets/a0479d9d-9855-493f-bb5c-94bffe23469b">

**Comment by ozhanefemeral** [comment]
Hey @AhmetSBulbul 👋

Thank you for the heads up.

Isn't CTRL key used for switching tabs on Windows devices? CTRL + 1-9 key combination is reserved for this purpose as far as I know.

Maybe we use CTRL for Mac and Alt on Windows, or use the other solution you offered. That would be great if you can test that behavior on Windows or open a branch/draft PR for me to test

Cheers

**Comment by AhmetSBulbul** [comment]
Okay, right now it's optional, both of them are working. I updated the PR as a draft. If we don't have more complex use case I'm gonna just create new Component to show the right key according to OS. I don't have a windows setup to test right now but I haven't changed the logic, I just added a "or" statement.

**Comment by ozhanefemeral** [comment]
we can implement showing the right key with:

1. using/creating a custom hook for getting OS details, and call that in `KeyCombinationLabel`
2. add a util function, and call that in `KeyCombinationLabel`

if you have spare time, that would be great if you can create an issue for this enhancement. I can also create the issue on Wednesday, latest.

and here is how you can change User Agent from Chrome Dev Tools:
https://developer.chrome.com/docs/devtools/device-mode/override-user-agent

So you can change Firefox/Opera/Chrome and Mac/Windows while working👍

**Comment by AhmetSBulbul** [comment]
Thanks for the trick. I'm gonna create an issue as soon as possible. If you have a chance to open before me, you can mention me in the comment.

**Comment by ozhanefemeral** [comment]
Closing this issue as completed thanks to PR by @AhmetSBulbul 💪
